SHELL = cmd.exe

#
# ZDS II Make File - in-ram-test project, Release configuration
#
# Generated by: ZDS II - eZ80Acclaim! 5.2.1 (Build 12102401)
#   IDE component: d:5.2.0:11111601
#   Install Path: C:\Program Files\ZiLOG\ZDSII_eZ80Acclaim!_5.2.1\
#

RM = del

ZDS = C:\PROG~FBU\ZiLOG\ZDSI~ZZT.1
BIN = $(ZDS)\bin
# ZDS include base directory
INCLUDE = C:\PROG~FBU\ZiLOG\ZDSI~ZZT.1\include
# intermediate files directory
WORKDIR = Y:\archive\devo\projects\zikzak\zik80\ez80-f93-assorted-tests\Release

CC = @$(BIN)\eZ80cc
AS = @$(BIN)\eZ80asm
LD = @$(BIN)\eZ80link
AR = @$(BIN)\eZ80lib
WEBTOC = @$(BIN)\mkwebpage

CFLAGS =  \
-define:NDEBUG -define:_EZ80F93 -define:_EZ80ACCLAIM!  \
-define:ZSL_DEVINIT -define:ZSL_DEVICE_PORTD  \
-define:_ZSL_PORT_USED -define:ZSL_DEVICE_PORTC  \
-define:ZSL_DEVICE_UART0 -define:_ZSL_UART_USED -genprintf  \
-NOkeepasm -keeplst -NOlist -NOlistinc -NOmodsect -optspeed  \
-promote -NOreduceopt  \
-stdinc:"..;$(INCLUDE)\std;$(INCLUDE)\zilog" -usrinc:"..;"  \
-NOmultithread -padbranch -debug -cpu:eZ80F93  \
-asmsw:"   \
	-define:_EZ80ACCLAIM!=1 -define:ZSL_DEVINIT=1  \
	-define:ZSL_DEVICE_PORTD=1 -define:_ZSL_PORT_USED=1  \
	-define:ZSL_DEVICE_PORTC=1 -define:ZSL_DEVICE_UART0=1  \
	-define:_ZSL_UART_USED=1  \
	-include:"..;$(INCLUDE)\std;$(INCLUDE)\zilog" -list -NOlistmac  \
	-pagelen:56 -pagewidth:80 -quiet -sdiopt -warn -debug -NOigcase  \
	-cpu:eZ80F93"

ASFLAGS =  \
-define:_EZ80ACCLAIM!=1 -define:ZSL_DEVINIT=1  \
-define:ZSL_DEVICE_PORTD=1 -define:_ZSL_PORT_USED=1  \
-define:ZSL_DEVICE_PORTC=1 -define:ZSL_DEVICE_UART0=1  \
-define:_ZSL_UART_USED=1  \
-include:"..;$(INCLUDE)\std;$(INCLUDE)\zilog" -list -NOlistmac  \
-name -pagelen:56 -pagewidth:80 -quiet -sdiopt -warn -debug  \
-NOigcase -cpu:eZ80F93

LDFLAGS = @.\in-ram-test_Release.linkcmd
OUTDIR = Y:\archive\devo\projects\zikzak\zik80\ez80-f93-assorted-tests\Release

build: in-ram-test

buildall: clean in-ram-test

relink: deltarget in-ram-test

deltarget: 
	@if exist $(WORKDIR)\in-ram-test.lod  \
            $(RM) $(WORKDIR)\in-ram-test.lod
	@if exist $(WORKDIR)\in-ram-test.hex  \
            $(RM) $(WORKDIR)\in-ram-test.hex
	@if exist $(WORKDIR)\in-ram-test.map  \
            $(RM) $(WORKDIR)\in-ram-test.map

clean: 
	@if exist $(WORKDIR)\in-ram-test.lod  \
            $(RM) $(WORKDIR)\in-ram-test.lod
	@if exist $(WORKDIR)\in-ram-test.hex  \
            $(RM) $(WORKDIR)\in-ram-test.hex
	@if exist $(WORKDIR)\in-ram-test.map  \
            $(RM) $(WORKDIR)\in-ram-test.map
	@if exist $(WORKDIR)\zsldevinit.obj  \
            $(RM) $(WORKDIR)\zsldevinit.obj
	@if exist $(WORKDIR)\main.obj  \
            $(RM) $(WORKDIR)\main.obj
	@if exist $(WORKDIR)\skeelib.obj  \
            $(RM) $(WORKDIR)\skeelib.obj
	@if exist $(WORKDIR)\lib_ay-3-8912.obj  \
            $(RM) $(WORKDIR)\lib_ay-3-8912.obj
	@if exist $(WORKDIR)\framebuffer.obj  \
            $(RM) $(WORKDIR)\framebuffer.obj

# pre-4.11.0 compatibility
rebuildall: buildall 

LIBS = 

OBJS =  \
            $(WORKDIR)\zsldevinit.obj  \
            $(WORKDIR)\main.obj  \
            $(WORKDIR)\skeelib.obj  \
            $(WORKDIR)\lib_ay-3-8912.obj  \
            $(WORKDIR)\framebuffer.obj

in-ram-test: $(OBJS)
	 $(LD) $(LDFLAGS)

$(WORKDIR)\zsldevinit.obj :  \
            Y:\archive\devo\projects\zikzak\zik80\EZ80~P1U\zsldevinit.asm  \
            $(INCLUDE)\zilog\intvect.inc
	 $(AS) $(ASFLAGS) Y:\archive\devo\projects\zikzak\zik80\EZ80~P1U\zsldevinit.asm

$(WORKDIR)\main.obj :  \
            Y:\archive\devo\projects\zikzak\zik80\EZ80~P1U\main.c  \
            $(INCLUDE)\zilog\cio.h  \
            $(INCLUDE)\zilog\defines.h  \
            $(INCLUDE)\zilog\eZ80190.h  \
            $(INCLUDE)\zilog\eZ80F91.h  \
            $(INCLUDE)\zilog\eZ80F92.h  \
            $(INCLUDE)\zilog\eZ80F93.h  \
            $(INCLUDE)\zilog\eZ80L92.h  \
            $(INCLUDE)\zilog\ez80.h  \
            $(INCLUDE)\zilog\gpio.h  \
            $(INCLUDE)\zilog\uart.h  \
            $(INCLUDE)\zilog\uartdefs.h  \
            $(INCLUDE)\std\Stdlib.h  \
            $(INCLUDE)\zilog\ez80.h  \
            $(INCLUDE)\zilog\gpio.h  \
            $(INCLUDE)\zilog\uart.h  \
            Y:\archive\devo\projects\zikzak\zik80\ez80-f93-assorted-tests\framebuffer.h  \
            Y:\archive\devo\projects\zikzak\zik80\ez80-f93-assorted-tests\lib_ay-3-8912.h  \
            Y:\archive\devo\projects\zikzak\zik80\ez80-f93-assorted-tests\skeelib.h
	 $(CC) $(CFLAGS) Y:\archive\devo\projects\zikzak\zik80\EZ80~P1U\main.c

$(WORKDIR)\skeelib.obj :  \
            Y:\archive\devo\projects\zikzak\zik80\EZ80~P1U\skeelib.c  \
            $(INCLUDE)\std\Format.h  \
            $(INCLUDE)\std\Stdarg.h  \
            $(INCLUDE)\std\Stdio.h  \
            $(INCLUDE)\zilog\cio.h  \
            $(INCLUDE)\zilog\defines.h  \
            $(INCLUDE)\zilog\eZ80190.h  \
            $(INCLUDE)\zilog\eZ80F91.h  \
            $(INCLUDE)\zilog\eZ80F92.h  \
            $(INCLUDE)\zilog\eZ80F93.h  \
            $(INCLUDE)\zilog\eZ80L92.h  \
            $(INCLUDE)\zilog\ez80.h  \
            $(INCLUDE)\zilog\gpio.h  \
            $(INCLUDE)\zilog\uart.h  \
            $(INCLUDE)\zilog\uartdefs.h  \
            $(INCLUDE)\std\Stdio.h  \
            $(INCLUDE)\zilog\ez80.h  \
            Y:\archive\devo\projects\zikzak\zik80\ez80-f93-assorted-tests\skeelib.h
	 $(CC) $(CFLAGS) Y:\archive\devo\projects\zikzak\zik80\EZ80~P1U\skeelib.c

$(WORKDIR)\lib_ay-3-8912.obj :  \
            Y:\archive\devo\projects\zikzak\zik80\EZ80~P1U\lib_ay-3-8912.c  \
            $(INCLUDE)\std\Format.h  \
            $(INCLUDE)\std\Stdarg.h  \
            $(INCLUDE)\std\Stdio.h  \
            $(INCLUDE)\zilog\cio.h  \
            $(INCLUDE)\zilog\defines.h  \
            $(INCLUDE)\zilog\eZ80190.h  \
            $(INCLUDE)\zilog\eZ80F91.h  \
            $(INCLUDE)\zilog\eZ80F92.h  \
            $(INCLUDE)\zilog\eZ80F93.h  \
            $(INCLUDE)\zilog\eZ80L92.h  \
            $(INCLUDE)\zilog\ez80.h  \
            $(INCLUDE)\zilog\gpio.h  \
            $(INCLUDE)\zilog\uart.h  \
            $(INCLUDE)\zilog\uartdefs.h  \
            $(INCLUDE)\std\Stdio.h  \
            $(INCLUDE)\zilog\ez80.h  \
            Y:\archive\devo\projects\zikzak\zik80\ez80-f93-assorted-tests\lib_ay-3-8912.h  \
            Y:\archive\devo\projects\zikzak\zik80\ez80-f93-assorted-tests\skeelib.h
	 $(CC) $(CFLAGS) Y:\archive\devo\projects\zikzak\zik80\EZ80~P1U\lib_ay-3-8912.c

$(WORKDIR)\framebuffer.obj :  \
            Y:\archive\devo\projects\zikzak\zik80\EZ80~P1U\framebuffer.c  \
            $(INCLUDE)\zilog\cio.h  \
            $(INCLUDE)\zilog\defines.h  \
            $(INCLUDE)\zilog\eZ80190.h  \
            $(INCLUDE)\zilog\eZ80F91.h  \
            $(INCLUDE)\zilog\eZ80F92.h  \
            $(INCLUDE)\zilog\eZ80F93.h  \
            $(INCLUDE)\zilog\eZ80L92.h  \
            $(INCLUDE)\zilog\ez80.h  \
            $(INCLUDE)\zilog\gpio.h  \
            $(INCLUDE)\zilog\uart.h  \
            $(INCLUDE)\zilog\uartdefs.h  \
            $(INCLUDE)\std\String.h  \
            $(INCLUDE)\zilog\ez80.h  \
            Y:\archive\devo\projects\zikzak\zik80\ez80-f93-assorted-tests\framebuffer.h  \
            Y:\archive\devo\projects\zikzak\zik80\ez80-f93-assorted-tests\skeelib.h
	 $(CC) $(CFLAGS) Y:\archive\devo\projects\zikzak\zik80\EZ80~P1U\framebuffer.c

