
# refering to libopencm3-examples Makefiles/ld-script
LCM3EX_BASE=/home/skeezix/archive/devo/toolkits/stm32/libopencm3-examples/examples/stm32/f4/

BINARY = vgatest

LDSCRIPT = ${LCM3EX_BASE}/stm32f4-discovery/stm32f4-discovery.ld

# copied libopencm3 Makefile.include into a local copy, hacked it up a touch
#include ${LCM3EX_BASE}/Makefile.include
include Makefile.libopencm3
